domain:
  default:  
    server:
      instances: 1
      restart: false
  gateway:
    inbound:
      groups:
        - alias: "casual-inbound"
          connections:
            - address: localhost:7771
  name: test-domain
  servers:    
    - instances: 1
      note: exampleserver
      path: ${CASUAL_HOME}/example/bin/casual-example-server

  executables:
    - alias: casual-inbound-server
      arguments:
        - -c
        - ${CASUAL_HOME}/nginx/conf/nginx.conf
        - -p
        - ${CASUAL_HOME}/nginx
      instances: 1
      note: nginx frontend
      path: ${CASUAL_HOME}/nginx/sbin/nginx
  queue:
    groups:
      - alias: QS_TEST
        queues:
        - name: QS_TEST.testQueue
          retry:
            count: 3
            delay: 60
        - name: QS_TEST.anotherTestQueue
          retry:
            count: 3
            delay: 60
